version: "3.9"

services:
  node-server:
    platform: linux/amd64
    build:
      context: ./Server/Server_Node
    container_name: node-server
    ports:
      - "5001:5001"
    env_file:
      - .env

  python-server:
    platform: linux/amd64
    build:
      context: ./Server/Server_Python
    container_name: python-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - node-server
